//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisacon.BLL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sisacon.BLL.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao excluir o Cliente..
        /// </summary>
        internal static string ErrDeleteClient {
            get {
                return ResourceManager.GetString("ErrDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao excluir o Equipamento.
        /// </summary>
        internal static string ErrDeleteEquip {
            get {
                return ResourceManager.GetString("ErrDeleteEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao Excluir Material.
        /// </summary>
        internal static string ErrDeleteMaterial {
            get {
                return ResourceManager.GetString("ErrDeleteMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao Excluir Categoria.
        /// </summary>
        internal static string ErrDeleteMaterialCategory {
            get {
                return ResourceManager.GetString("ErrDeleteMaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao excluir Fornecedor.
        /// </summary>
        internal static string ErrDeleteProvider {
            get {
                return ResourceManager.GetString("ErrDeleteProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O E-mail informado já está em uso..
        /// </summary>
        internal static string ErrEmailInUse {
            get {
                return ResourceManager.GetString("ErrEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O E-mail ou a Senha informada está incorreta..
        /// </summary>
        internal static string ErrFailedLogon {
            get {
                return ResourceManager.GetString("ErrFailedLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar as Áreas de Atuação.
        /// </summary>
        internal static string ErrFailedToLoadOccupation {
            get {
                return ResourceManager.GetString("ErrFailedToLoadOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar novo Cliente.
        /// </summary>
        internal static string ErrInsertClient {
            get {
                return ResourceManager.GetString("ErrInsertClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar Empresa..
        /// </summary>
        internal static string ErrInsertCompany {
            get {
                return ResourceManager.GetString("ErrInsertCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar novo Equipamento..
        /// </summary>
        internal static string ErrInsertEquip {
            get {
                return ResourceManager.GetString("ErrInsertEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao Salvar Material.
        /// </summary>
        internal static string ErrInsertMaterial {
            get {
                return ResourceManager.GetString("ErrInsertMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar novo Fornecedor..
        /// </summary>
        internal static string ErrInsertProvider {
            get {
                return ResourceManager.GetString("ErrInsertProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar novo Usuário..
        /// </summary>
        internal static string ErrInsertUser {
            get {
                return ResourceManager.GetString("ErrInsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida, esta Categoria está sendo utilizado no momento..
        /// </summary>
        internal static string ErrMaterialCategoryInUse {
            get {
                return ResourceManager.GetString("ErrMaterialCategoryInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida, este Material está sendo utilizado no momento..
        /// </summary>
        internal static string ErroMaterialInUse {
            get {
                return ResourceManager.GetString("ErroMaterialInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar os dados do Cliente..
        /// </summary>
        internal static string ErrUpdateClient {
            get {
                return ResourceManager.GetString("ErrUpdateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar os dados da sua Empresa.
        /// </summary>
        internal static string ErrUpdateCompany {
            get {
                return ResourceManager.GetString("ErrUpdateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel atualizar as Configurações.
        /// </summary>
        internal static string ErrUpdateConfig {
            get {
                return ResourceManager.GetString("ErrUpdateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel atualizar as Configurações de Custo.
        /// </summary>
        internal static string ErrUpdateCostConfig {
            get {
                return ResourceManager.GetString("ErrUpdateCostConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar os dados do Equipamento.
        /// </summary>
        internal static string ErrUpdateEquip {
            get {
                return ResourceManager.GetString("ErrUpdateEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar os dados so Fornecedor.
        /// </summary>
        internal static string ErrUpdateProvider {
            get {
                return ResourceManager.GetString("ErrUpdateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar os dados do Usuário..
        /// </summary>
        internal static string ErrUpdateUser {
            get {
                return ResourceManager.GetString("ErrUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao Atualizar Material.
        /// </summary>
        internal static string ErrUpdMaterial {
            get {
                return ResourceManager.GetString("ErrUpdMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desculpe, mas o seu acesso ao sistema foi suspenso.
        ///Entre em contato com o suporte para mais informações..
        /// </summary>
        internal static string ErrUserNotActive {
            get {
                return ResourceManager.GetString("ErrUserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete seus dados, criando sua nova Empresa..
        /// </summary>
        internal static string NotifyCreateCompany {
            get {
                return ResourceManager.GetString("NotifyCreateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! Algo de errado aconteceu, favor tente novamente mais tarde..
        /// </summary>
        internal static string ProcessError {
            get {
                return ResourceManager.GetString("ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SucD {
            get {
                return ResourceManager.GetString("SucD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cliente foi excluído com Sucesso!.
        /// </summary>
        internal static string SucDeleteClient {
            get {
                return ResourceManager.GetString("SucDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Equipamento foi excluído com Sucesso!.
        /// </summary>
        internal static string SucDeleteEquip {
            get {
                return ResourceManager.GetString("SucDeleteEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Material foi Excluído com Sucesso!.
        /// </summary>
        internal static string SucDeleteMaterial {
            get {
                return ResourceManager.GetString("SucDeleteMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Categoria foi Excluída com Sucesso!.
        /// </summary>
        internal static string SucDeleteMaterialCategory {
            get {
                return ResourceManager.GetString("SucDeleteMaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Fornecedor foi excluído com Sucesso!.
        /// </summary>
        internal static string SucDeleteProvider {
            get {
                return ResourceManager.GetString("SucDeleteProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cliente foi salvo com Sucesso!.
        /// </summary>
        internal static string SucInsertClient {
            get {
                return ResourceManager.GetString("SucInsertClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua nova Empresa foi criada com Sucesso!.
        /// </summary>
        internal static string SucInsertCompany {
            get {
                return ResourceManager.GetString("SucInsertCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Equipamento foi salvo com Sucesso!.
        /// </summary>
        internal static string SucInsertEquip {
            get {
                return ResourceManager.GetString("SucInsertEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Material foi Salvo com Sucesso!.
        /// </summary>
        internal static string SucInsertMaterial {
            get {
                return ResourceManager.GetString("SucInsertMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Categoria foi criada com Sucesso!.
        /// </summary>
        internal static string SucInsertMaterialCategory {
            get {
                return ResourceManager.GetString("SucInsertMaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Pesquisa de Preço foi Salva com Sucesso!.
        /// </summary>
        internal static string SucInsertPrice {
            get {
                return ResourceManager.GetString("SucInsertPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor criado com Sucesso!.
        /// </summary>
        internal static string SucInsertProvider {
            get {
                return ResourceManager.GetString("SucInsertProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário criado com Sucesso!.
        /// </summary>
        internal static string SucInsertUser {
            get {
                return ResourceManager.GetString("SucInsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dados do Cliente foram atualizados com Sucesso!.
        /// </summary>
        internal static string SucUpdateClient {
            get {
                return ResourceManager.GetString("SucUpdateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados da sua Empresa foram atualizados com Sucesso!.
        /// </summary>
        internal static string SucUpdateCompany {
            get {
                return ResourceManager.GetString("SucUpdateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações atualizadas com Sucesso!.
        /// </summary>
        internal static string SucUpdateConfig {
            get {
                return ResourceManager.GetString("SucUpdateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações de Custo Atualizadas com Sucesso!.
        /// </summary>
        internal static string SucUpdateCostConfig {
            get {
                return ResourceManager.GetString("SucUpdateCostConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Fornecedor foi atualizado com Sucesso!.
        /// </summary>
        internal static string SucUpdateProvider {
            get {
                return ResourceManager.GetString("SucUpdateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados do Usuário foram atualizados com Sucesso!.
        /// </summary>
        internal static string SucUpdateUser {
            get {
                return ResourceManager.GetString("SucUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados do Equipamento foram atualizados com Sucesso!.
        /// </summary>
        internal static string SucUpdEquip {
            get {
                return ResourceManager.GetString("SucUpdEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Material foi Atualizado com Sucesso!.
        /// </summary>
        internal static string SucUpdMaterial {
            get {
                return ResourceManager.GetString("SucUpdMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Categoria foi Atualizada com Sucesso!.
        /// </summary>
        internal static string SucUpdMaterialCategory {
            get {
                return ResourceManager.GetString("SucUpdMaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Pesquisa de Preço foi Atualizada com Sucesso!.
        /// </summary>
        internal static string SucUpdPrice {
            get {
                return ResourceManager.GetString("SucUpdPrice", resourceCulture);
            }
        }
    }
}
